### ISSUE TITLE
Tome of Mysteries - Investigating Phenomena

### ISSUE THREAD

**Issue by Arrckeus** [brian-frederick/Discord-MonsterBot#6]
When investigating a mystery that is not a monster, but a phenomenon, certain questions become available to the Hunters when they use **investigate a mystery**
Those questions being
• How is this phenomenon doing this?
• What could fix it, cure it, or slow it down?
• How far does the effect reach?
• What will be affected next?

![Alt Weird Moves   Phenomena-2](https://user-images.githubusercontent.com/74620493/99432504-39a49100-28da-11eb-933f-ee6eddaef593.jpg)

**Comment by brian-frederick** [comment]
@Arrckeus Hopefully this does the trick? A custom move called Investigate Phenomena (`ip`) which you could call in place of Investigate a mystery (`aim`). Example below:

![image](https://user-images.githubusercontent.com/21226878/99600368-e9edc480-29c2-11eb-9ee2-1ab9f6819023.png)
